Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources


	''' <summary>
	'''   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
	''' </summary>
	' Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
	' tramite uno strumento quale ResGen o Visual Studio.
	' Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
	' con l'opzione /str oppure ricompilare il progetto VS.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
		'''   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _1() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_1", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _10() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_10", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _11() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_11", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _12() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_12", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _13() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_13", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _14() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_14", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _2() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_2", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _3() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_3", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _4() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_4", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _5() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_5", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _6() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_6", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _7() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_7", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _8() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_8", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property _9() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_9", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property
	End Module
End Namespace
